/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./components/common/AppHeader.vue')['default']
    Button: typeof import('./components/ui/Button.vue')['default']
    Input: typeof import('./components/ui/Input.vue')['default']
    LoginForm: typeof import('./components/features/auth/LoginForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const AppHeader: typeof import('./components/common/AppHeader.vue')['default']
  const Button: typeof import('./components/ui/Button.vue')['default']
  const Input: typeof import('./components/ui/Input.vue')['default']
  const LoginForm: typeof import('./components/features/auth/LoginForm.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}